### PR TITLE
fix: enable image selection from gallery and used tabs in MediaModal

### LINKED ISSUE #406: (SP: ) MediaModal fails to select images from "Галерея" and "Використані" tabs
## Description
In the MediaModal file picker flow, the image selection mechanism is broken for existing assets. Users can currently only pick and confirm images from the "Завантаження" (Uploads) tab. Attempting to select an image from the "Галерея" (Gallery) or "Використані" (Used) tabs fails to register the selection or pass the asset data back to the parent component.

## Steps to Reproduce

1. Go to [About us](https://lf-admin-stage-dzfpbxeuauh7fad2.polandcentral-01.azurewebsites.net/about-us).
2. Open `Фундація Лятошинського` section, scroll to block with image preview.

Image

3. Press the "Змінити зображення" to select an image.

Image

4. Navigate to the "Галерея" or "Використані" tab.

Image

5. Click on an image in the grid and then click "Застосувати".

Image

6. **Contrast:** Uploading an image strictly from the "Завантаження" tab works perfectly.

## Actual Result

As a result we've got preview block unchanged.

Image

## Expected Result

1. The image selection logic (onSelect or active state selection) must work universally across all three tabs.
2. Clicking an image in "Галерея" or "Використані" and application of the selection should change the preview image .

### PR DESCRIPTION
**Pull request by dest411**
## Description

Fixed a bug where the MediaModal failed to process images selected from the "Галерея" (Gallery) and "Використані" (Used) tabs.
The issue occurred because the onImageChange handler strictly expects a File object, but selecting an existing image only provided a URL string.

## Type of change

- [ ] New feature
- [X] Bug fix
- [ ] Documentation update
- [ ] Refactoring / Tech debt
- [ ] CI/CD improvement
- [ ] Other: 

## How to test

1. Navigate to the About us page.
2. Open the "Фундація Лятошинського" section.
3. Click "Змінити зображення" to open the Media Modal.
4. Navigate to the "Галерея" or "Використані" tab.
5. Select any existing image and click "Застосувати" (Apply).
6. Verify that the image is successfully selected, the modal closes, and the preview is updated.

### Actual result: 
As a result we've got preview block unchanged.
image

### Expected result: 
1. The image selection logic (onSelect or active state selection) must work universally across all three tabs.
2. Clicking an image in "Галерея" or "Використані" and application of the selection should change the preview image .

https://github.com/user-attachments/assets/a19bfff1-dd04-47e4-b01b-b7b08e6960e5

Closes: https://github.com/Liatoshynsky-Foundation/lf-admin/issues/406

### CODE REVIEW

**Review by navimov — APPROVED** [review]

File: app/shared/components/design-system/photo-block/PhotoBlock.tsx [hunk 1]
```diff
@@ -100,13 +100,28 @@ export const ImagePreviewBlock = ({
...
+        const blob = await response.blob();
+        const file = new File([blob], selected.fileName || 'image.jpg', {
+          type: blob.type
+        });
+
+        setPreviewImage(selected.src);
+        onChangeImage(file);
+      }
+    } catch (error) {
+      console.error('Помилка при обробці зображення з MediaModal:', error);
```
Comment (Fedorieieva) [inline app/shared/components/design-system/photo-block/PhotoBlock.tsx]: According to our guidelines, we should avoid using console.* methods. Since we have a Toast component in our project, please use it here instead of console.error. This will provide better feedback to the user if the image processing fails

**Review by Fedorieieva — CHANGES_REQUESTED** [review]

File: app/shared/components/design-system/photo-block/PhotoBlock.tsx (hunk 1 above)
Comment (dest411) [reply app/shared/components/design-system/photo-block/PhotoBlock.tsx]: Done, thanks!

**Review by kandyba — APPROVED** [review]

**Review by DenisGordProgrammer — APPROVED** [review]

**Review by Fedorieieva — APPROVED** [review]
